{{- $name := .Values.name -}}

{{ if .Values.deployment }}
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ $name }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
    spec:
      containers:
        - name: {{ $name }}
          image: {{ .Values.deployment.image }}
          imagePullPolicy: IfNotPresent
{{- end }}
